plugins:
  - jekyll-feed
title: Blog de Gabriel P. Alves
description: Seja bem-vindo(a) ao meu blog
author: Gabriel Proen√ßa Alves
baseurl: ""
url: "https://gabrielproencaalves.github.io"
feed:
  icon: img/favicon.ico
  logo: img/favicon.ico
